### ISSUE TITLE
SHT36 Pro SPI issue with TMC5160

### ISSUE THREAD

**Issue by godefroi** [Mellow-3D/klipper-docs#280]
Several people (of which I am one) have reported issues with recent Klipper versions and SPI communication with the TMC5160 on the SHT36 Pro. Initially, when I used a mid-September 2023 version of Klipper, everything worked. When I updated to a mid-March 2024 version, I get errors when communicating with the TMC5160:

```
Unable to write tmc spi 'extruder' register IHOLD_IRUN
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown
```

Several people have reported this issue in the Voron discord (and probably the Klipper discord).

**Comment by FengHua741** [comment]
SHT36PRO may not be able to use the 5160spi driver due to differences in the upper computer. Here are the available firmware
https://mellow.klipper.cn/#/board/fly_sht36_pro/flash
